# osrs-flips Configuration

# Discord bot settings
discord:
  token: "" # Set via DISCORD_TOKEN environment variable
  channel_id: "" # Set via DISCORD_CHANNEL_ID environment variable
  guild_id: "" # Optional, set via DISCORD_GUILD_ID environment variable

# LLM configuration
llm:
  base_url: "http://localhost:11434" # Ollama server URL (or configure via LLM_BASE_URL)
  model: "qwen3:4b" # Model to use for analysis
  timeout: "20m" # Timeout for LLM requests

# OSRS Wiki Real Time Prices API configuration
osrs:
  user_agent: "" # Set one here or via OSRS_API_USER_AGENT
  max_concurrent_calls: 3
  rate_limit_delay_ms: 1000 # Please respect this amazing *free* community resource if you use this program
  volume_data_max_items: 1000

# Logging configuration (structured for Fluent Bit ingestion)
logging:
  level: "info" # debug, info, warn, error, fatal
  format: "json" # json or text

# Trading analysis jobs
jobs:
  - name: "under-1m"
    description: "Viable margins with buy in under 1M"
    enabled: true
    filters:
      # pricing api filters
      margin_pct_min: 5
      margin_gp_min: 1000
      insta_sell_price_max: 1000000

      # Sort before fetching volume information
      sort_by: "margin_gp"
      sort_desc: true
      limit: 500 # max items to query osrs volume api for

      # volume api filters
      volume_1h_min: 20
    output:
      max_items: 25 # max items to pass into llm
    model:
      name: qwen3:8b
      num_ctx: 18000
      temperature: 0.9

  - name: "midrange"
    description: "Viable margins with buy in between 600k and 3.5M"
    enabled: true
    filters:
      margin_pct_min: 3
      insta_sell_price_min: 600000
      insta_sell_price_max: 3500000
      max_hours_since_update: 1
      sort_by: "margin_gp"
      sort_desc: true
      limit: 500
      volume_1h_min: 20
    output:
      max_items: 25 # max items to pass into llm
    model:
      name: qwen3:4b
      num_ctx: 18000
      temperature: 0.5

  - name: "trade-limited"
    description: "Viable margins on items with daily trade limits"
    enabled: true
    filters:
      buy_limit_max: 1000 # These refer to the in-game daily trade limit for an item

      margin_pct_min: 5
      max_hours_since_update: 1
      sort_by: "margin_gp"
      sort_desc: true
      limit: 500
      volume_20m_min: 20
    output:
      max_items: 25 # max items to pass into llm
    model:
      name: qwen3:8b
      num_ctx: 18000
      temperature: 0.9

  - name: "active-items"
    description: "Viable margins on highly active items"
    enabled: true
    filters:
      margin_pct_min: 3
      max_hours_since_update: 1
      sort_by: "margin_gp"
      sort_desc: true
      limit: 500
      volume_20m_min: 50
    output:
      max_items: 20 # max items to pass into llm
    model:
      name: qwen3:8b
      num_ctx: 18000
      temperature: 0.9

# Job schedules (cron format with seconds: second minute hour day month weekday)
schedules:
  - job_name: "under-1m"
    cron: "0 0 * * * *"
    enabled: false
  - job_name: "midrange"
    cron: "0 0 * * * * "
    enabled: true
  - job_name: "trade-limited"
    cron: "0 30 * * * * "
    enabled: false
  - job_name: "active-items"
    cron: "0 30 * * * *"
    enabled: true

