# osrs-flips Configuration

# Discord bot settings
discord:
  token: "" # Set via DISCORD_TOKEN environment variable
  channel_id: "" # Set via DISCORD_CHANNEL_ID environment variable
  guild_id: "" # Optional, set via DISCORD_GUILD_ID environment variable

# LLM configuration
llm:
  base_url: "http://localhost:11434" # Ollama server URL (or configure via LLM_BASE_URL)
  model: "qwen3:14b" # Model to use for analysis
  timeout: "20m" # Timeout for LLM requests

# OSRS Wiki Real Time Prices API configuration
osrs:
  user_agent: "" # Set one here or via OSRS_API_USER_AGENT
  max_concurrent_calls: 3
  rate_limit_delay_ms: 1000 # Please respect this amazing *free* community resource if you use this program
  volume_data_max_items: 1000

# Logging configuration (structured for Fluent Bit ingestion)
logging:
  level: "info" # debug, info, warn, error, fatal
  format: "json" # json or text

# Trading analysis jobs
jobs:
  - name: "Tempting Trades Under 1M"
    description: "Looking for Margins + Recent Volume Trends, up to a 1M buy limit"
    enabled: true
    filters:
      # pricing api filters
      margin_gp_min: 3000
      margin_pct_min: 3.5 # At least 3.5% margin
      insta_sell_price_min: 8000
      insta_sell_price_max: 1000000

      # Sort before fetching volume information
      sort_by: "margin_gp"
      sort_desc: true
      limit: 500 # max items to query osrs volume api for

      # volume api filters
      volume_1h_min: 20
    output:
      max_items: 50 # max items to pass into llm
    model:
      name: qwen3:4b # Override global model for this job
      num_ctx: 35000 # Larger context for better analysis
      timeout: "20m" # Job-specific timeout

  - name: "1M+ Wonders"
    description: "Looking for Margins + Recent Volume Trends, up to 10M buy limit"
    enabled: true
    filters:
      # pricing api filters
      margin_gp_min: 15000
      margin_pct_min: 2.5
      insta_sell_price_min: 1000000
      insta_sell_price_max: 5000000
      max_hours_since_update: 2
      sort_by: "margin_gp"
      sort_desc: true
      limit: 500 # max items to pass query osrs volume api

      # volume api filters
      volume_24h_min: 30
    output:
      max_items: 45 # max items to pass into llm
    model:
      name: qwen3:4b # Override global model for this job
      num_ctx: 35000 # Larger context for better analysis
      # temperature: 0.0
      timeout: "20m" # Job-specific timeout

  - name: "Daily Trade Limited"
    description: "Looking for Margins + Recent Volume Trends, up to 10M buy limit"
    enabled: false
    filters:
      # pricing api filters
      buy_limit_max: 100 # These refer to the in-game daily trade limit for an item
      buy_limit_min: 20

      margin_gp_min: 4000
      margin_pct_min: 4.0
      max_hours_since_update: 1
      sort_by: "margin_gp"
      sort_desc: true
      limit: 500 # max items to pass query osrs volume api

      # volume api filters
      volume_24h_min: 100
    output:
      max_items: 50 # max items to pass into llm
    model:
      name: qwen3:4b # Override global model for this job
      num_ctx: 30000 # Larger context for better analysis
      # temperature: 0.0
      timeout: "20m" # Job-specific timeout

# Job schedules (cron format with seconds: second minute hour day month weekday)
schedules:
  - job_name: "Tempting Trades Under 1M"
    cron: "0 0 * * * *" # at min 0
    enabled: false
  - job_name: "1M+ Wonders"
    cron: "0 0/20 * * * * " # every 20 mi
    enabled: true
