services:
  collector:
    container_name: osrs-flips-collector
    restart: unless-stopped
    image: osrs-flips-collector:latest
    env_file:
      - ~/osrs-flips/.env
    command:
      - ./osrs-flips-collector
      - -sync-timestamps-per-cycle=300
      - -enable-signals
      # - -sync-min-item-threshold=5000

    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "osrs-flips-collector"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

    networks:
      - caddy_network

  ui:
    container_name: osrs-flips-ui
    restart: unless-stopped
    image: osrs-flips-ui:latest
    env_file:
      - ~/osrs-flips/.env

    networks:
      - caddy_network

networks:
  caddy_network:
    driver: bridge
